sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
   - yes '' | pecl -q install -f mongo-1.5.8 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - ant travis -keep-going

notifications:
    email: toon.verwerft@phpro.be
