language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - pecl install -f mongo-1.4.1

matrix:
  allow_failures:
    - php: hhvm

script:
  - ant travis -keep-going

notifications:
    email: toon.verwerft@phpro.be
